name: Publish to WinGet
on:
  release:
    types: [released]
permissions:
  contents: read
jobs:
  publish:
    runs-on: windows-latest
    steps:
      - uses: vedantmgoyal2009/winget-releaser@v1
        with:
          identifier: Jackett.Jackett
          token: ${{ secrets.WINGET }}
